### PR TITLE
Fix Issue#35

### PR DESCRIPTION
**Pull request by xcvb85**
First very basic canvas ND added. Fixes rain bug.

### CODE REVIEW

**Comment by HHS81** [comment]
Looks great! 😄 
But the canvas ND is a real framerate eater. I only get half of the former framerates, when I switch to The ND-Page.
The flap indicator on the Flight Control Page shows not the correct values.
Otherwise it is really, really great!

**Comment by xcvb85** [comment]
Can you have a look if reducing the quality can improve the framerate?
In mfd1.nas, mfd2.nas and eicas.nas:
"size": [1024, 1024]
to
"size": [512, 512]
(could be even more realistic for a CRT screen)

Maybe reducing refresh rate can improve the situation.
In nd.nas:
settimer(func me.fast_update(), 0.1);
to
settimer(func me.fast_update(), 0.3);

The flap values are calculated from the output of the FDM (100%->35°). Maybe we must change it there?

**Comment by HHS81** [comment]
I will try.
For the flaps, we just need the property from fdm/jsbsim/..., I guess I can change it.

**Comment by xcvb85** [comment]
I guess the main problem is the refresh rate of the mapstructure framework. I will check how to change this.

**Comment by HHS81** [comment]
o.k., size and the refresh rate improves things a lot.

**Comment by xcvb85** [comment]
In do328-110-set.xml line 194 you define the flaps settings (provided that 35° is the maximum):
0.000 -> 0°
0.375 -> 13.125°
0.625 -> 21.875°
1.000 -> 35°

**Comment by xcvb85** [comment]
OK my fault. 32° is the maximum. I will fix it.

**Comment by HHS81** [comment]
Seems I did something wrong. I don't get the improvements with master.....

**Comment by xcvb85** [comment]
I got the updates. Did you run "git pull"?
One question: Do we really need "settimer(func me.fast_update(), 0.3);"? The animation is not really fluid now and you mentioned that the CitationX works ok for you. After looking into the CitationX code I found some ideas for performance improvements and I will try to decrease the refresh rate of the mapstructure framework.

**Comment by HHS81** [comment]
I did. I noticed that I have to startup to get the CDU working.

**Comment by HHS81** [comment]
I'm not sure if we need "settimer(func me.fast_update(), 0.3);"
The Citation X works pretty well, so if you have ideas how to improve go on

**Comment by xcvb85** [comment]
Can you please check if branch issue17 has better performance now?

**Comment by HHS81** [comment]
I checked and: wow! You are a magician! Perfomance is great!

**Pull request merged**
